### ISSUE TITLE
无法就通过import_tables挂载其他词库的rime词库进行转换

### ISSUE THREAD

**Issue by wold9168** [studyzy/imewlconverter#300]
软件无法就通过import_tables挂载其他词库的rime词库进行转换。

下述yaml脚本通过`import_tables`挂载了配置目录下的`example.dict.yaml`：

```yaml
# example_core.dict.yaml
name: rime_x
version: "0.1.0"
import_tables:
  - example # 挂载配置目录下的 example.dict.yaml
```

在`example.dict.yaml`有内容的情况下，无法就指令`imewlconverter -i:rime ./example_core.dict.yaml -o:wb86 ./example1.txt `对词库文件`example_core.dict.yaml`进行转换（转换出来的文件系空文件）。除`wb86`外，其他的目标词库格式也是如此。

软件似乎无法正确读取rime词库中通过`import_tables`挂载的词库文件。

# 软件版本
所使用的软件版本为`2.8.0.0`，平台为`Linux`。
